input {
  tcp {
    port => 5000
    codec => json_lines
  }

  udp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "project" => "zero-trust-cruise-platform"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "zero-trust-audit-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}